package main.java.org.ortega.bankapp;


/**
* bankapp/OperationsBancaires.java.
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationsBancaires.idl
* vendredi 5 juillet 2024 10 h 38 CEST
*/

public interface OperationsBancaires extends OperationsBancairesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface OperationsBancaires
