package main.java.org.ortega.bankapp;


/**
* bankapp/OperationsBancairesOperations.java.
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationsBancaires.idl
* vendredi 5 juillet 2024 10 h 38 CEST
*/

public interface OperationsBancairesOperations 
{
  double balance ();
  void depot (double amount);
  void retrait (double amount);
} // interface OperationsBancairesOperations
