package main.java.org.ortega.bankapp;


/**
* bankapp/OperationsBancairesPOA.java.
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationsBancaires.idl
* vendredi 5 juillet 2024 10 h 38 CEST
*/

public abstract class OperationsBancairesPOA extends org.omg.PortableServer.Servant
 implements OperationsBancairesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("balance", new java.lang.Integer (0));
    _methods.put ("depot", new java.lang.Integer (1));
    _methods.put ("retrait", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // bankapp/OperationsBancaires/balance
       {
         double $result = (double)0;
         $result = this.balance ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // bankapp/OperationsBancaires/depot
       {
         double amount = in.read_double ();
         this.depot (amount);
         out = $rh.createReply();
         break;
       }

       case 2:  // bankapp/OperationsBancaires/retrait
       {
         double amount = in.read_double ();
         this.retrait (amount);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:bankapp/OperationsBancaires:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public OperationsBancaires _this()
  {
    return OperationsBancairesHelper.narrow(
    super._this_object());
  }

  public OperationsBancaires _this(org.omg.CORBA.ORB orb)
  {
    return OperationsBancairesHelper.narrow(
    super._this_object(orb));
  }


} // class OperationsBancairesPOA
