package main.java.org.ortega.bankapp;

/**
* bankapp/OperationsBancairesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationsBancaires.idl
* vendredi 5 juillet 2024 10 h 38 CEST
*/

public final class OperationsBancairesHolder implements org.omg.CORBA.portable.Streamable
{
  public OperationsBancaires value = null;

  public OperationsBancairesHolder ()
  {
  }

  public OperationsBancairesHolder (OperationsBancaires initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OperationsBancairesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OperationsBancairesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OperationsBancairesHelper.type ();
  }

}
