package main.java.org.ortega.bankapp;


import org.omg.CORBA.Any;

/**
* bankapp/OperationsBancairesHelper.java.
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationsBancaires.idl
* vendredi 5 juillet 2024 10 h 38 CEST
*/

abstract public class OperationsBancairesHelper
{
  private static String  _id = "IDL:bankapp/OperationsBancaires:1.0";

  public static void insert (org.omg.CORBA.Any a, OperationsBancaires that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OperationsBancaires extract (Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (OperationsBancairesHelper.id (), "OperationsBancaires");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OperationsBancaires read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OperationsBancairesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OperationsBancaires value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static OperationsBancaires narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OperationsBancaires)
      return (OperationsBancaires)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _OperationsBancairesStub stub = new _OperationsBancairesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static OperationsBancaires unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OperationsBancaires)
      return (OperationsBancaires)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _OperationsBancairesStub stub = new _OperationsBancairesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
